// Site delivery only. The local chatbot has no endpoint and never calls this Worker.
import catalog from './catalog.json' with {type:'json'};
const COOKIE='__Host-vftech-session',SESSION_SECONDS=7*24*3600,CODE_SECONDS=600;
const encoder=new TextEncoder();
const TOPICS=new Set(['Website rebuild','Platform migration','AI integration','Support plan','Advisory or fractional leadership','Not sure yet']);
const PLAN_IDS=new Set([...catalog.builds,...catalog.plans].map(p=>p.id));
class HTTPError extends Error{constructor(status,message){super(message);this.status=status;}}
function json(value,status=200,headers={}){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',...headers}});}
function now(){return Math.floor(Date.now()/1000);}
function field(value,name,max,required=false){if(typeof value!=='string')value='';value=value.trim();if(value.length>max||(required&&!value))throw new HTTPError(400,`Check ${name}.`);return value;}
function email(value){const text=field(value,'your email address',254,true).toLowerCase();if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(text)||/[\r\n]/.test(text))throw new HTTPError(400,'Enter a valid email address.');return text;}
function origin(env){try{const url=new URL(env.SITE_URL);if(url.protocol!=='https:' && !(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))return '';return url.origin;}catch{return '';}}
function ready(env){const base=Boolean(env.DB&&origin(env)&&env.RESEND_API_KEY&&env.TURNSTILE_SECRET_KEY&&env.TURNSTILE_SITE_KEY&&env.TURNSTILE_HOSTNAME&&env.EMAIL_FROM&&!/[\r\n]/.test(env.EMAIL_FROM));return {contactEnabled:Boolean(base&&env.CONTACT_TO),accountsEnabled:Boolean(base&&env.SESSION_SECRET?.length>=32)};}
function config(env){return {apiBase:'/api',...ready(env),turnstileSiteKey:env.TURNSTILE_SITE_KEY||''};}
function requireReady(env,kind){if(!ready(env)[kind])throw new HTTPError(503,'Live delivery is not configured yet. Please use the request preview.');}
function sameOrigin(request,env){const expected=origin(env);if(!expected||new URL(request.url).origin!==expected||request.headers.get('Origin')!==expected)throw new HTTPError(403,'Submit this form from the VFTech site.');}
async function body(request){if(!request.headers.get('Content-Type')?.startsWith('application/json'))throw new HTTPError(415,'Send a JSON request.');if(Number(request.headers.get('Content-Length'))>16384)throw new HTTPError(413,'This request is too large.');const reader=request.body?.getReader();if(!reader)throw new HTTPError(400,'The request is empty.');let size=0,chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>16384){await reader.cancel();throw new HTTPError(413,'This request is too large.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}try{const result=JSON.parse(new TextDecoder().decode(bytes));if(!result||typeof result!=='object'||Array.isArray(result))throw Error();return result;}catch{throw new HTTPError(400,'The request could not be read.');}}
function random(){const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');}
function code(){const n=new Uint32Array(1);do{crypto.getRandomValues(n);}while(n[0]>=4294000000);return String(n[0]%1000000).padStart(6,'0');}
async function digest(text){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function hmac(env,text){const key=await crypto.subtle.importKey('raw',encoder.encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function limit(env,label,value,max,seconds){const timestamp=now(),bucket=Math.floor(timestamp/seconds),key=await digest(`${label}:${value}:${bucket}`);const row=await env.DB.prepare('INSERT INTO rate_limits (key,hits,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET hits=hits+1 RETURNING hits').bind(key,(bucket+1)*seconds).first();if(row.hits>max)throw new HTTPError(429,'Too many attempts. Please try again later.');}
async function captcha(request,env,input,action){const token=field(input.turnstileToken,'verification',2048,true);try{const fields={secret:env.TURNSTILE_SECRET_KEY,response:token};const ip=request.headers.get('CF-Connecting-IP');if(ip)fields.remoteip=ip;const response=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams(fields),signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error();const result=await response.json();if(result.success!==true||result.hostname!==env.TURNSTILE_HOSTNAME||result.action!==action)throw new HTTPError(400,'Verification failed. Please try the CAPTCHA again.');}catch(error){if(error instanceof HTTPError)throw error;throw new HTTPError(503,'Verification is temporarily unavailable. Please try again.');}}
async function send(env,payload,key){try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from:env.EMAIL_FROM,...payload}),signal:AbortSignal.timeout(10000)});if(!response.ok||!(await response.json()).id)throw Error();}catch{throw new HTTPError(502,'Email delivery could not be accepted. Please try again.');}}
function uuid(value,name){if(typeof value!=='string'||! /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(value))throw new HTTPError(400,`Check ${name}.`);return value.toLowerCase();}
async function contact(request,env,input){
  requireReady(env,'contactEnabled');if(input.website)throw new HTTPError(400,'The request could not be verified.');
  const key=uuid(input.idempotencyKey,'the request identifier');
  const data={name:field(input.name,'your name',80,true),email:email(input.email),business:field(input.business,'the business name',160),phone:field(input.phone,'the phone number',40),times:field(input.times,'your availability',300),message:field(input.message,'your message',4000,true),planId:field(input.planId,'the selected plan',40),topics:input.topics??[]};
  if(data.planId&&!PLAN_IDS.has(data.planId))throw new HTTPError(400,'Choose a published plan.');if(!Array.isArray(data.topics)||data.topics.length>6||data.topics.some(topic=>!TOPICS.has(topic)))throw new HTTPError(400,'Choose a listed topic.');
  const hash=await digest(JSON.stringify(data));
  const prior=await env.DB.prepare('SELECT id,body_hash,status FROM contact_requests WHERE idempotency_key=?').bind(key).first();
  if(prior){if(!equal(prior.body_hash,hash))throw new HTTPError(409,'This request identifier has already been used.');if(prior.status==='sent')return json({accepted:true,requestId:prior.id});if(prior.status==='pending')throw new HTTPError(409,'This request is still processing. Please wait before retrying.');}
  await limit(env,'contact-ip',request.headers.get('CF-Connecting-IP')||'unknown',5,3600);await captcha(request,env,input,'contact');
  const id=prior?.id||crypto.randomUUID();
  const claim=prior?await env.DB.prepare("UPDATE contact_requests SET status='pending' WHERE id=? AND status='failed'").bind(id).run():await env.DB.prepare("INSERT OR IGNORE INTO contact_requests (id,idempotency_key,body_hash,email,name,business,phone,topics,times,message,plan_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'pending',?)").bind(id,key,hash,data.email,data.name,data.business,data.phone,JSON.stringify(data.topics),data.times,data.message,data.planId,now()).run();
  if(claim.meta.changes!==1)throw new HTTPError(409,'This request is already processing.');
  try{const selected=[...catalog.builds,...catalog.plans].find(p=>p.id===data.planId);await send(env,{to:[env.CONTACT_TO],reply_to:data.email,subject:`VFTech project request ${id}`,text:[`Request: ${id}`,`Name: ${data.name}`,`Email: ${data.email}`,`Business: ${data.business||'—'}`,`Phone: ${data.phone||'—'}`,`Topics: ${data.topics.join(', ')||'Not selected'}`,`Plan: ${selected?`${selected.name} (${selected.price})`:'Not selected'}`,`Availability: ${data.times||'—'}`,'',data.message].join('\n')},`contact-${id}`);await env.DB.prepare("UPDATE contact_requests SET status='sent' WHERE id=?").bind(id).run();return json({accepted:true,requestId:id},201);}catch(error){await env.DB.prepare("UPDATE contact_requests SET status='failed' WHERE id=?").bind(id).run();throw error;}
}
async function requestCode(request,env,input){
  requireReady(env,'accountsEnabled');if(input.website)throw new HTTPError(400,'The request could not be verified.');const address=email(input.email),name=field(input.name,'your name',80);
  await limit(env,'code-ip',request.headers.get('CF-Connecting-IP')||'unknown',10,3600);await limit(env,'code-email',address,3,900);await captcha(request,env,input,'account');
  const id=crypto.randomUUID(),value=code(),timestamp=now(),hash=await hmac(env,`code:${id}:${address}:${value}`);
  await env.DB.prepare('INSERT INTO auth_challenges (id,email,name,code_hash,expires_at,created_at) VALUES (?,?,?,?,?,?)').bind(id,address,name,hash,timestamp+CODE_SECONDS,timestamp).run();
  try{await send(env,{to:[address],subject:'Your VFTech verification code',text:`Your VFTech verification code is ${value}.\n\nIt expires in ten minutes and can be used once. If you did not request it, ignore this email. Never share your code.`},`code-${id}`);}catch(error){await env.DB.prepare('DELETE FROM auth_challenges WHERE id=?').bind(id).run();throw error;}
  return json({challengeId:id,expiresIn:CODE_SECONDS},201);
}
async function verifyCode(request,env,input){
  requireReady(env,'accountsEnabled');const id=uuid(input.challengeId,'the verification request'),address=email(input.email),value=field(input.code,'the verification code',6,true);if(!/^\d{6}$/.test(value))throw new HTTPError(400,'Enter the six-digit code.');
  await limit(env,'verify-ip',request.headers.get('CF-Connecting-IP')||'unknown',30,900);
  const timestamp=now(),row=await env.DB.prepare('UPDATE auth_challenges SET attempts=attempts+1 WHERE id=? AND email=? AND consumed=0 AND expires_at>? AND attempts<5 RETURNING *').bind(id,address,timestamp).first();
  if(!row||!equal(row.code_hash,await hmac(env,`code:${id}:${address}:${value}`)))throw new HTTPError(400,'The code is invalid or expired. Request a new code.');const claimed=await env.DB.prepare('UPDATE auth_challenges SET consumed=1 WHERE id=? AND consumed=0 AND expires_at>?').bind(id,timestamp).run();if(claimed.meta.changes!==1)throw new HTTPError(400,'This code has already been used. Request a new code.');
  const token=random(),tokenHash=await digest(token);await env.DB.batch([env.DB.prepare('INSERT INTO customers (id,email,name,created_at) VALUES (?,?,?,?) ON CONFLICT(email) DO NOTHING').bind(crypto.randomUUID(),address,row.name,timestamp),env.DB.prepare('INSERT INTO sessions (token_hash,customer_id,expires_at,created_at) SELECT ?,id,?,? FROM customers WHERE email=?').bind(tokenHash,timestamp+SESSION_SECONDS,timestamp,address)]);
  const profile=await env.DB.prepare('SELECT id,email,name FROM customers WHERE email=?').bind(address).first();return json({authenticated:true,customer:profile,csrfToken:await hmac(env,`csrf:${token}`)},200,{'Set-Cookie':`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${SESSION_SECONDS}`});
}
async function session(request,env){requireReady(env,'accountsEnabled');const token=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const customer=await env.DB.prepare('SELECT c.id,c.email,c.name FROM sessions s JOIN customers c ON c.id=s.customer_id WHERE s.token_hash=? AND s.expires_at>?').bind(await digest(token),now()).first();return customer?{customer,token,csrfToken:await hmac(env,`csrf:${token}`)}:null;}
async function cleanup(env){if(!env.DB)return;const timestamp=now();await env.DB.batch([env.DB.prepare('DELETE FROM auth_challenges WHERE expires_at<=?').bind(timestamp),env.DB.prepare('DELETE FROM sessions WHERE expires_at<=?').bind(timestamp),env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<=?').bind(timestamp),env.DB.prepare('DELETE FROM contact_requests WHERE created_at<?').bind(timestamp-30*24*3600)]);}
export default {
  async fetch(request,env){const url=new URL(request.url);if(url.pathname.endsWith('/services-config.js'))return new Response(`window.VFTechServices = Object.freeze(${JSON.stringify(config(env))});\n`,{headers:{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});if(!url.pathname.startsWith('/api/'))return env.ASSETS?env.ASSETS.fetch(request):new Response('Not found',{status:404});
    try{if(request.method==='GET'&&url.pathname==='/api/config')return json(config(env));if(request.method==='GET'&&url.pathname==='/api/prices')return json(catalog);if(origin(env)&&url.origin!==origin(env))throw new HTTPError(403,'Use the configured VFTech site.');
      if(request.method==='POST'){sameOrigin(request,env);const input=await body(request);if(url.pathname==='/api/contact')return await contact(request,env,input);if(url.pathname==='/api/auth/request-code')return await requestCode(request,env,input);if(url.pathname==='/api/auth/verify-code')return await verifyCode(request,env,input);
        if(url.pathname==='/api/auth/logout'){const active=await session(request,env);if(!active)throw new HTTPError(401,'Sign in to continue.');if(!equal(request.headers.get('X-CSRF-Token'),active.csrfToken))throw new HTTPError(403,'Refresh your account page and try again.');await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(active.token)).run();return json({authenticated:false},200,{'Set-Cookie':`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`});}}
      if(request.method==='GET'&&['/api/session','/api/account/requests'].includes(url.pathname)){const active=await session(request,env);if(url.pathname==='/api/session')return json(active?{authenticated:true,customer:active.customer,csrfToken:active.csrfToken}:{authenticated:false});if(!active)throw new HTTPError(401,'Sign in to see your requests.');const result=await env.DB.prepare('SELECT id,business,topics,message,plan_id AS planId,status,created_at AS createdAt FROM contact_requests WHERE email=? ORDER BY created_at DESC LIMIT 50').bind(active.customer.email).all();return json({requests:result.results});}
      throw new HTTPError(404,'This endpoint was not found.');
    }catch(error){return json({error:error instanceof HTTPError?error.message:'The service is temporarily unavailable. Please try again.'},error instanceof HTTPError?error.status:500);}
  },async scheduled(controller,env,ctx){ctx.waitUntil(cleanup(env));}
};
