import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './backend-fixture.mjs';
function setup(t){const f=fixture();t.after(()=>f.close());return f;}
test('Unconfigured services fail closed and do not contact providers',async t=>{const f=setup(t);f.env.RESEND_API_KEY='';assert.equal((await f.request('config')).body.accountsEnabled,false);assert.equal((await f.request('contact',f.contact())).status,503);assert.equal((await f.request('auth/request-code',{email:'one@example.test'})).status,503);assert.equal(f.state.outbound.length,0);});
test('Published prices are served without changing plan values',async t=>{const f=setup(t);const result=await f.request('prices');assert.equal(result.body.builds[0].price,'$3,500 Fixed');assert.equal(result.body.plans[1].price,'$750/mo');});
test('Contact acceptance, validated plan and idempotency reflect provider acceptance',async t=>{const f=setup(t),data=f.contact();const first=await f.request('contact',data);assert.equal(first.status,201);assert.equal(first.body.accepted,true);assert.equal(f.state.emails.length,1);assert.match(f.state.emails[0].payload.text,/Business \(\$7,500–14,000\)/);assert.equal(f.state.emails[0].payload.reply_to,data.email);assert.equal(f.state.emails[0].payload.to[0],f.env.CONTACT_TO);assert.equal((await f.request('contact',data)).status,200);assert.equal(f.state.emails.length,1);assert.equal((await f.request('contact',{...data,message:'Changed'})).status,409);});
test('CAPTCHA checks success, hostname, action and one-time token use',async t=>{const f=setup(t);f.state.hostname='wrong.test';assert.equal((await f.request('contact',f.contact())).status,400);f.state.hostname=null;f.state.action='account';assert.equal((await f.request('contact',f.contact())).status,400);f.state.action=null;f.state.failCaptcha=true;assert.equal((await f.request('contact',f.contact())).status,400);f.state.failCaptcha=false;const data=f.contact();assert.equal((await f.request('contact',data)).status,201);assert.equal((await f.request('contact',{...data,idempotencyKey:crypto.randomUUID()})).status,400);assert.equal(f.state.emails.length,1);});
test('Provider failure is not success and a fresh CAPTCHA permits retry',async t=>{const f=setup(t),data=f.contact();f.state.failMail=true;const result=await f.request('contact',data);assert.equal(result.status,502);assert.equal(result.body.accepted,undefined);assert.equal(f.sqlite.prepare('SELECT status FROM contact_requests').get().status,'failed');f.state.failMail=false;assert.equal((await f.request('contact',{...data,turnstileToken:f.token('contact')})).status,201);assert.equal(f.state.emails.length,1);});
test('Honeypot, schema limits, bad plans and header injection are rejected',async t=>{const f=setup(t);for(const override of [{website:'bot'},{message:'x'.repeat(4001)},{email:'x@example.test\r\nBcc: other@example.test'},{planId:'free-unlimited'},{topics:['Unlisted topic']}])assert.equal((await f.request('contact',f.contact(override))).status,400);assert.equal(f.state.emails.length,0);const huge=await f.worker.fetch(new Request('https://vftech.test/api/contact',{method:'POST',headers:{Origin:'https://vftech.test','Content-Type':'application/json'},body:JSON.stringify({message:'x'.repeat(18000)})}),f.env);assert.equal(huge.status,413);});
test('Mutations reject missing or foreign origins',async t=>{const f=setup(t);assert.equal((await f.request('contact',f.contact(),{headers:{Origin:'https://evil.test'}})).status,403);assert.equal((await f.request('contact',f.contact(),{headers:{Origin:''}})).status,403);assert.equal(f.state.outbound.length,0);});
test('Atomic IP rate limits stop repeated contact submissions',async t=>{const f=setup(t);for(let i=0;i<5;i++)assert.equal((await f.request('contact',f.contact())).status,201);assert.equal((await f.request('contact',f.contact())).status,429);assert.equal(f.state.emails.length,5);});
test('Codes are stored as keyed hashes and create an account only after verification',async t=>{const f=setup(t),data=await f.challenge();assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM customers').get().n,0);const row=f.sqlite.prepare('SELECT * FROM auth_challenges').get();assert.equal(row.code_hash.length,64);assert.notEqual(row.code_hash,data.code);assert.ok(row.expires_at-row.created_at===600);const result=await f.request('auth/verify-code',data);assert.equal(result.status,200);assert.equal(result.body.authenticated,true);assert.equal(result.body.customer.email,data.email);const cookie=result.response.headers.get('Set-Cookie');for(const flag of ['__Host-vftech-session=','Path=/','HttpOnly','Secure','SameSite=Strict','Max-Age=604800'])assert.ok(cookie.includes(flag),flag);const raw=cookie.split(';')[0].split('=')[1];assert.notEqual(f.sqlite.prepare('SELECT token_hash FROM sessions').get().token_hash,raw);assert.equal((await f.request('auth/verify-code',data)).status,400);});
test('Five wrong attempts and expired codes cannot authenticate',async t=>{const f=setup(t),data=await f.challenge();const wrong=data.code==='111111'?'222222':'111111';for(let i=0;i<5;i++)assert.equal((await f.request('auth/verify-code',{...data,code:wrong})).status,400);assert.equal((await f.request('auth/verify-code',data)).status,400);const expired=await f.challenge('expired@example.test');f.sqlite.prepare('UPDATE auth_challenges SET expires_at=0 WHERE id=?').run(expired.challengeId);assert.equal((await f.request('auth/verify-code',expired)).status,400);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM customers').get().n,0);});
test('Concurrent verification cannot reuse a code',async t=>{const f=setup(t),data=await f.challenge();const replies=await Promise.all([f.request('auth/verify-code',data),f.request('auth/verify-code',data)]);assert.deepEqual(replies.map(r=>r.status).sort(),[200,400]);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM sessions').get().n,1);});
test('Email delivery failure does not leave a usable code',async t=>{const f=setup(t);f.state.failMail=true;const reply=await f.request('auth/request-code',{email:'one@example.test',turnstileToken:f.token('account')});assert.equal(reply.status,502);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM auth_challenges').get().n,0);});
test('Each verified customer sees only their own requests',async t=>{const f=setup(t);await f.request('contact',f.contact({email:'one@example.test',message:'First private request'}));await f.request('contact',f.contact({email:'two@example.test',message:'Second private request'}));const one=await f.login('one@example.test'),two=await f.login('two@example.test');assert.equal((await f.request('account/requests')).status,401);const first=await f.request('account/requests',undefined,{headers:{Cookie:one.cookie}}),second=await f.request('account/requests',undefined,{headers:{Cookie:two.cookie}});assert.deepEqual(first.body.requests.map(r=>r.message),['First private request']);assert.deepEqual(second.body.requests.map(r=>r.message),['Second private request']);});
test('Sign-out requires CSRF and removes the session',async t=>{const f=setup(t),login=await f.login();assert.equal((await f.request('session',undefined,{headers:{Cookie:login.cookie}})).body.authenticated,true);assert.equal((await f.request('auth/logout',{}, {headers:{Cookie:login.cookie}})).status,403);const result=await f.request('auth/logout',{}, {headers:{Cookie:login.cookie,'X-CSRF-Token':login.body.csrfToken}});assert.equal(result.status,200);assert.match(result.response.headers.get('Set-Cookie'),/Max-Age=0/);assert.equal((await f.request('session',undefined,{headers:{Cookie:login.cookie}})).body.authenticated,false);});
test('Expired sessions and scheduled cleanup remove retained request bodies',async t=>{const f=setup(t),login=await f.login();f.sqlite.prepare('UPDATE sessions SET expires_at=0').run();assert.equal((await f.request('session',undefined,{headers:{Cookie:login.cookie}})).body.authenticated,false);await f.request('contact',f.contact());f.sqlite.prepare('UPDATE contact_requests SET created_at=0').run();let task;await f.worker.scheduled({},f.env,{waitUntil(value){task=value;}});await task;assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM contact_requests').get().n,0);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM sessions').get().n,0);});
