(function(){
  var tbody=document.querySelector('[data-ledger-projects]');if(!tbody)return;
  var rows=Array.from(tbody.rows),search=document.getElementById('ld-search'),filter=document.getElementById('ld-filter'),count=document.getElementById('ld-result-count'),empty=document.getElementById('ld-empty'),order=1,sortButton=document.querySelector('[data-ledger-sort]');
  function update(){var term=search.value.trim().toLowerCase(),stage=filter.value,visible=0;rows.forEach(function(row){var match=(!term||row.textContent.toLowerCase().includes(term))&&(stage==='all'||(stage==='active'?row.dataset.stage!=='Complete':row.dataset.stage===stage));row.hidden=!match;if(match)visible++;});count.textContent=visible+' of '+rows.length+' projects';empty.hidden=visible!==0;}
  search.addEventListener('input',update);filter.addEventListener('change',update);
  sortButton.addEventListener('click',function(){order*=-1;rows.sort(function(a,b){return a.dataset.project.localeCompare(b.dataset.project)*order;}).forEach(function(row){tbody.appendChild(row);});sortButton.closest('th').setAttribute('aria-sort',order===1?'ascending':'descending');sortButton.setAttribute('aria-label','Project: sort '+(order===1?'descending':'ascending'));});
  var dialog=document.getElementById('ld-project-dialog'),opener;
  rows.forEach(function(row){row.querySelector('button').addEventListener('click',function(event){opener=event.currentTarget;document.getElementById('ld-dialog-title').textContent=row.dataset.project;document.getElementById('ld-dialog-client').textContent=row.dataset.client;document.getElementById('ld-dialog-stage').textContent=row.dataset.stage;document.getElementById('ld-dialog-owner').textContent=row.dataset.owner;document.getElementById('ld-dialog-next').textContent=row.dataset.next;dialog.showModal();});});
  dialog.addEventListener('close',function(){if(opener)opener.focus();});dialog.addEventListener('click',function(event){if(event.target===dialog){var box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});
  var reviews=Array.from(document.querySelectorAll('[data-ledger-review]'));reviews.forEach(function(input){input.addEventListener('change',function(){document.getElementById('ld-review-count').textContent=reviews.filter(function(item){return item.checked;}).length+' of '+reviews.length+' reviewed';});});update();
})();
