(function(){
  'use strict';
  var settings=window.VFTechServices||{},catalog=window.VFTechPrices||{builds:[],plans:[]};
  var contact=document.getElementById('book-form'),signin=document.getElementById('vf-account-form');
  function element(tag,cls,text){var node=document.createElement(tag);if(cls)node.className=cls;if(text)node.textContent=text;return node;}
  function plan(id){return catalog.builds.concat(catalog.plans).find(function(p){return p.id===id;});}
  var api;
  try{api=settings.apiBase?new URL(settings.apiBase.replace(/\/$/,'')+'/',location.origin):null;if(api&&api.origin!==location.origin)api=null;}catch{api=null;}
  async function call(path,data,csrf){var headers={'Accept':'application/json'};if(data!==undefined)headers['Content-Type']='application/json';if(csrf)headers['X-CSRF-Token']=csrf;var response=await fetch(new URL(path,api),{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:headers,body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});var result;try{result=await response.json();}catch{throw Error('The service could not respond. Please try again.');}if(!response.ok)throw Error(result.error||'The request could not be completed.');return result;}
  var loader;
  function loadCaptcha(){if(window.turnstile)return Promise.resolve();if(loader)return loader;loader=new Promise(function(resolve,reject){window.vfTechTurnstileReady=resolve;var script=element('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit&onload=vfTechTurnstileReady';script.async=true;script.onerror=function(){reject(Error('Verification could not load. Please try again.'));};document.head.append(script);});return loader;}
  function verification(container,action,submit,status){var token='',widget=null;submit.disabled=true;loadCaptcha().then(function(){widget=turnstile.render(container,{sitekey:settings.turnstileSiteKey,action:action,size:'flexible',callback:function(value){token=value;submit.disabled=false;},'expired-callback':function(){token='';submit.disabled=true;status.textContent='Verification expired. Please verify again.';},'error-callback':function(){token='';submit.disabled=true;status.textContent='Verification could not complete. Please try again.';}});}).catch(function(error){status.textContent=error.message;});return {get:function(){return token;},reset:function(){token='';submit.disabled=true;if(widget!==null)turnstile.reset(widget);}};}
  function trap(form){var box=element('div','vfs-trap'),label=element('label','','Leave this field empty'),input=element('input');input.name='website';input.autocomplete='off';input.tabIndex=-1;input.setAttribute('aria-hidden','true');label.append(input);box.append(label);box.setAttribute('aria-hidden','true');form.append(box);return input;}
  if(contact){
    Object.entries({name:80,email:254,business:160,phone:40,times:300,message:4000}).forEach(function(pair){var input=contact.elements.namedItem(pair[0]);if(input)input.maxLength=pair[1];});
    var selected=plan(new URLSearchParams(location.search).get('plan')),selection=element('input');selection.type='hidden';selection.name='planId';selection.value=selected?selected.id:'';contact.append(selection);
    if(selected){var note=element('p','vfs-contact-status','Selected: '+selected.name+' · '+selected.price+'. This requests a discussion; it does not purchase or activate a plan.');contact.prepend(note);}
    var honey=trap(contact),submit=contact.querySelector('button[type=submit]'),hint=document.getElementById('submit-hint');
    if(api&&settings.contactEnabled&&settings.turnstileSiteKey){
      submit.firstChild.textContent='Send my request ';hint.textContent='Complete verification, then send your request to VFTech. Avoid passwords, payment details and sensitive documents. Requests are retained for up to 31 days in the portal.';
      var container=element('div');container.id='vf-contact-captcha';contact.querySelector('.submit-row').before(container);
      var status=element('p','vfs-contact-status');status.id='vf-contact-status';status.setAttribute('role','status');container.after(status);
      var captcha=verification(container,'contact',submit,status),key=crypto.randomUUID(),lastBody='';
      contact.addEventListener('submit',async function(event){
        event.preventDefault();event.stopImmediatePropagation();if(!contact.reportValidity())return;if(!captcha.get()){status.textContent='Complete verification before sending.';return;}
        var fd=new FormData(contact),payload={name:fd.get('name'),email:fd.get('email'),business:fd.get('business'),phone:fd.get('phone'),times:fd.get('times'),topics:fd.getAll('topic'),message:fd.get('message'),planId:selection.value,website:honey.value};
        var fingerprint=JSON.stringify(payload);if(lastBody&&lastBody!==fingerprint)key=crypto.randomUUID();lastBody=fingerprint;payload.idempotencyKey=key;payload.turnstileToken=captcha.get();submit.disabled=true;status.textContent='Sending your request…';
        try{var result=await call('contact',payload);status.textContent='Your request was accepted for email delivery. Reference: '+result.requestId+'.';contact.reset();selection.value=selected?selected.id:'';key=crypto.randomUUID();lastBody='';document.getElementById('form-out').hidden=true;}catch(error){status.textContent=error.message||'The request could not be sent. Please try again.';}finally{captcha.reset();}
      },true);
    }else{hint.textContent='Email delivery is not enabled. This form prepares a request for you to copy; nothing is sent.';var output=document.querySelector('#form-out>p');if(output)output.textContent='Nothing has been sent. Copy this request for your records. A business inbox still needs to be configured.';}
  }
  if(signin&&api&&settings.accountsEnabled&&settings.turnstileSiteKey){
    var accountStatus=document.getElementById('vf-service-status'),codeForm=document.getElementById('vf-code-form'),home=document.getElementById('vf-account-home'),signSubmit=signin.querySelector('button[type=submit]'),state={email:'',challengeId:'',csrf:''};
    accountStatus.textContent='Enter your email and complete verification to receive a sign-in code.';
    var accountCaptcha=verification(document.getElementById('vf-account-captcha'),'account',signSubmit,accountStatus),accountHoney=trap(signin);
    function showLoggedOut(){home.hidden=true;signin.hidden=false;codeForm.hidden=true;document.getElementById('vf-account-title').textContent='Create an account or sign in';state.csrf='';state.challengeId='';codeForm.reset();}
    async function showAccount(result){state.csrf=result.csrfToken;signin.hidden=true;codeForm.hidden=true;home.hidden=false;document.getElementById('vf-account-title').textContent='Your customer account';document.getElementById('vf-profile').textContent=(result.customer.name||'Customer')+' · '+result.customer.email;accountStatus.textContent='You are signed in.';var list=document.getElementById('vf-requests');list.textContent='Loading your requests…';try{var data=await call('account/requests');list.textContent='';if(!data.requests.length)list.append(element('p','vfs-small','No requests yet. Send a project request using this verified email address.'));data.requests.forEach(function(request){var item=element('article','vfs-request'),selectedPlan=plan(request.planId);item.append(element('strong','',request.business||'Project request'),element('p','',new Date(request.createdAt*1000).toLocaleDateString()+' · '+(request.status==='sent'?'Accepted for email delivery':request.status==='failed'?'Delivery failed':'Processing')),element('p','',request.message));if(selectedPlan)item.append(element('p','',selectedPlan.name+' · '+selectedPlan.price));list.append(item);});}catch(error){list.textContent=error.message;}}
    signin.addEventListener('submit',async function(event){event.preventDefault();if(!signin.reportValidity())return;if(!accountCaptcha.get()){accountStatus.textContent='Complete verification to receive a code.';return;}signSubmit.disabled=true;var fd=new FormData(signin);state.email=String(fd.get('email')).trim().toLowerCase();accountStatus.textContent='Requesting your verification code…';try{var result=await call('auth/request-code',{name:fd.get('name'),email:state.email,website:accountHoney.value,turnstileToken:accountCaptcha.get()});state.challengeId=result.challengeId;signin.hidden=true;codeForm.hidden=false;accountStatus.textContent='A code was accepted for delivery to '+state.email+'. Check your email.';document.getElementById('vf-code').focus();}catch(error){accountStatus.textContent=error.message;}finally{accountCaptcha.reset();}});
    codeForm.addEventListener('submit',async function(event){event.preventDefault();if(!codeForm.reportValidity())return;var submit=codeForm.querySelector('button[type=submit]');submit.disabled=true;accountStatus.textContent='Verifying your code…';try{var result=await call('auth/verify-code',{email:state.email,challengeId:state.challengeId,code:document.getElementById('vf-code').value});codeForm.reset();await showAccount(result);}catch(error){accountStatus.textContent=error.message;}finally{submit.disabled=false;}});
    document.getElementById('vf-change-email').addEventListener('click',function(){showLoggedOut();accountCaptcha.reset();accountStatus.textContent='Enter your email and complete verification for a new code.';document.getElementById('vf-email').focus();});
    document.getElementById('vf-logout').addEventListener('click',async function(){this.disabled=true;try{await call('auth/logout',{},state.csrf);showLoggedOut();accountCaptcha.reset();accountStatus.textContent='You are signed out.';}catch(error){accountStatus.textContent=error.message;}finally{this.disabled=false;}});
    call('session').then(function(result){if(result.authenticated)showAccount(result);}).catch(function(){accountStatus.textContent='The account service could not be reached. Please try again later.';signSubmit.disabled=true;});
  }
})();
